<a href="https://colab.research.google.com/github/HelloBebizz/Coingecko-API-and-Data/blob/main/btcusdmlck.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pip install rpy2

In [ ]:
#pip install pandasql

In [ ]:
import requests as r
import pandas as pd 
import numpy as np
import json 
#import pandasql as ps
import matplotlib.pyplot as plt

In [ ]:
response  = r.get("https://api.coingecko.com/api/v3/coins/bitcoin/ohlc?vs_currency=usd&days=30").json()
print (response)

[[1676073600000, 21499.66, 21518.88, 21499.66, 21518.88], [1676088000000, 21643.7, 21719.06, 21643.7, 21677.76], [1676102400000, 21682.01, 21707.99, 21682.01, 21683.69], [1676116800000, 21696.95, 21706.48, 21686.17, 21686.17], [1676131200000, 21704.54, 21765.11, 21704.54, 21761.94], [1676145600000, 21739.75, 21808.2, 21713.47, 21808.2], [1676160000000, 21681.23, 21851.02, 21681.23, 21851.02], [1676174400000, 21889.58, 21889.58, 21821.11, 21838.46], [1676188800000, 21809.13, 21835.42, 21792.25, 21835.42], [1676203200000, 21814.92, 21989.57, 21814.92, 21989.57], [1676217600000, 21903.32, 21939.76, 21819.22, 21939.76], [1676232000000, 21936.67, 22077.09, 21936.67, 21989.38], [1676246400000, 22011.58, 22067.79, 21798.02, 21829.31], [1676260800000, 21779.87, 21779.87, 21728.46, 21753.44], [1676275200000, 21820.13, 21861.31, 21820.13, 21834.09], [1676289600000, 21899.57, 21899.57, 21624.52, 21689.39], [1676304000000, 21607.91, 21705.21, 21598.08, 21705.21], [1676318400000, 21626.55, 21626.55

In [ ]:
res_df = pd.DataFrame(response)
print (res_df)

In [ ]:
X = res_df.iloc[:,[0,1,2,3]].values
Y = res_df.iloc[:,[4]].values
print (Y)

[[21518.88]
 [21677.76]
 [21683.69]
 [21686.17]
 [21761.94]
 [21808.2 ]
 [21851.02]
 [21838.46]
 [21835.42]
 [21989.57]
 [21939.76]
 [21989.38]
 [21829.31]
 [21753.44]
 [21834.09]
 [21689.39]
 [21705.21]
 [21625.96]
 [21654.22]
 [21729.42]
 [21752.91]
 [21819.55]
 [22275.83]
 [22142.02]
 [22201.  ]
 [22096.14]
 [22123.79]
 [22192.49]
 [22728.21]
 [22867.17]
 [24104.33]
 [24683.6 ]
 [24683.85]
 [24617.56]
 [24417.16]
 [24960.7 ]
 [23949.13]
 [23842.08]
 [23666.45]
 [23736.2 ]
 [24095.65]
 [24331.66]
 [24597.1 ]
 [24566.26]
 [24641.4 ]
 [24485.69]
 [24695.04]
 [24694.12]
 [24614.83]
 [24671.99]
 [24611.24]
 [24648.18]
 [24722.67]
 [24447.43]
 [24480.53]
 [24330.87]
 [24515.34]
 [24890.78]
 [24972.05]
 [24791.71]
 [24695.  ]
 [24915.14]
 [24982.46]
 [24705.24]
 [24744.27]
 [24693.17]
 [24370.93]
 [24177.12]
 [23979.69]
 [24169.67]
 [24005.6 ]
 [23808.36]
 [24090.25]
 [24631.75]
 [24380.95]
 [24271.6 ]
 [24004.62]
 [23900.04]
 [23807.76]
 [23959.09]
 [23890.01]
 [23859.52]
 [23797.47]
 [23

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 1/3)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [ ]:
lr.fit(X_train, Y_train)
Y_pred = lr.predict(X_test)
print (Y_pred)

[[20048.40506527]
 [22299.58998666]
 [24691.42223048]
 [23050.33576126]
 [23519.19187961]
 [21704.24513031]
 [20572.07939453]
 [24745.34039133]
 [20086.84481014]
 [24575.63943952]
 [20362.68582449]
 [24785.37587306]
 [23194.83520419]
 [23729.01411468]
 [22121.53767759]
 [23325.76736029]
 [24675.43651196]
 [23890.89596673]
 [22064.39274656]
 [24079.71834941]
 [23327.99383198]
 [21975.61783514]
 [23884.67275666]
 [21710.58642559]
 [24173.57445014]
 [23209.87177417]
 [21634.71819481]
 [21167.38113975]
 [21869.20802073]
 [24657.04816608]
 [23422.21773865]
 [22053.96849286]
 [24664.17598414]
 [22512.37525108]
 [21980.87018606]
 [23000.78826879]
 [23447.59627192]
 [21512.58662316]
 [22130.03883092]
 [21715.78623523]
 [23627.45622231]
 [23512.25131523]
 [22353.74081049]
 [20351.973501  ]
 [19697.39304097]
 [22522.3499873 ]
 [20355.27264088]
 [23308.13085485]
 [24469.16832196]
 [21642.89489214]
 [22119.14224244]
 [23020.24187612]
 [23706.24263032]
 [24689.46974307]
 [24730.86106134]
 [22182.26

In [ ]:
Yloc = res_df.iloc[:,[4]]
yluc = Yloc.iloc[:61].values
#print (ylu
avg = (Y_pred / yluc) 
print (avg)

[[0.93166582]
 [1.02868516]
 [1.13870943]
 [1.06290487]
 [1.08074886]
 [0.99523322]
 [0.94146998]
 [1.1331083 ]
 [0.91992024]
 [1.11760437]
 [0.92811798]
 [1.1271521 ]
 [1.06255467]
 [1.09081663]
 [1.01316509]
 [1.07544598]
 [1.13684394]
 [1.10473227]
 [1.01894193]
 [1.10816204]
 [1.07240796]
 [1.00715266]
 [1.0722237 ]
 [0.98051517]
 [1.0888507 ]
 [1.05040391]
 [0.97789385]
 [0.9538083 ]
 [0.96220547]
 [1.07827283]
 [0.97170167]
 [0.89346645]
 [0.99920296]
 [0.91448443]
 [0.90022223]
 [0.9214801 ]
 [0.97905837]
 [0.90229488]
 [0.93508062]
 [0.91488049]
 [0.98056937]
 [0.96632335]
 [0.90879579]
 [0.82845226]
 [0.79936177]
 [0.91981684]
 [0.82426563]
 [0.94387372]
 [0.99408236]
 [0.87722534]
 [0.89874148]
 [0.93395301]
 [0.95888683]
 [1.00990042]
 [1.01022572]
 [0.91169229]
 [0.89865216]
 [0.95940288]
 [0.79541853]
 [0.90516294]
 [0.90858583]]
